//ARRAY DE MONTAÑAS
export const montanas = [
    {
        id: 0,
        nombre: "Laguna Negra",
        dificultad: "Media",
        altura: 1730,
        desnivel: 800,
        estaciones: 0,
        peso: 0,
        tiempo: 5,
        img: "/calculadoraMontana_DiPaola/img/galerias/lagunaNegra.jpg",
        elemento1: "Mochila cómoda con varillas interiores",
        elemento2: "Bolsa de dormir pero es un cerro que podrás realizar en el día",
        elemento3: "Carpa de montaña (opcional)",
        elemento4: "Traje de baño en verano",
        elemento5: "Ropa de abrigo para la cumbre",
        elemento6: "Zapatillas de trekking",
        elemento7: "Comida para 2 días y 1 noche si pernoctas",
        elemento8: "1.5 litros de agua",
        elemento9: "Protección solar",
        elemento10: "GPS, radio, mapa y botiquín",
    },
    {
        id: 1,
        nombre: "Cerro Catedral",
        dificultad: "Alta",
        altura: 2000,
        desnivel: 1050,
        estaciones: 0,
        peso: 0,
        tiempo: 8,
        img: "/calculadoraMontana_DiPaola/img/galerias/cerroCatedral.jpg",
        elemento1: "Mochila cómoda con varillas interiores",
        elemento2: "Bolsa de dormir o similar + aislante",
        elemento3: "Carpa de montaña con varillas de aluminio",
        elemento4: "Grampones y piqueta",
        elemento5: "Ropa de abrigo y nieve para la cumbre",
        elemento6: "Zapatillas de trekking",
        elemento7: "Comida para 2 días y 1 noche",
        elemento8: "1.5 litros de agua",
        elemento9: "Protección solar",
        elemento10: "GPS, radio, mapa y botiquín",
    },
    {
        id: 2,
        nombre: "Cerro Tronador",
        dificultad: "Media",
        altura: 2000,
        desnivel: 1050,
        estaciones: 0,
        peso: 0,
        tiempo: 8,
        img: "/calculadoraMontana_DiPaola/img/galerias/cerroTronador.jpeg",
        elemento1: "Mochila cómoda con varillas interiores",
        elemento2: "Bolsa de dormir o similar + aislante",
        elemento3: "Carpa de montaña con varillas de aluminio",
        elemento4: "Sogas (por el terreno de este cerro no pueden clavarse estacas)",
        elemento5: "Ropa de abrigo y nieve para la cumbre",
        elemento6: "Zapatillas de trekking",
        elemento7: "Comida para 2 días y 1 noche",
        elemento8: "1 litro de agua (hay agua en todo el recorrido)",
        elemento9: "Protección solar",
        elemento10: "GPS, radio, mapa y botiquín",
    },
    {
        id: 3,
        nombre: "Laguna Jakob",
        dificultad: "Media",
        altura: 1600,
        desnivel: 850,
        estaciones: 0,
        peso: 0,
        tiempo: 7.5,
        img: "/calculadoraMontana_DiPaola/img/galerias/lagunaJakob.jpeg",
        elemento1: "Mochila cómoda con varillas interiores",
        elemento2: "Bolsa de dormir o similar + aislante",
        elemento3: "Carpa de montaña con varillas de aluminio",
        elemento4: "Sogas aptas para colgarse en piedras",
        elemento5: "Ropa de abrigo y nieve para la cumbre",
        elemento6: "2 pares de zapatillas de trekking",
        elemento7: "Comida para 3 días y 2 noches",
        elemento8: "1 litro de agua (hay agua en todo el recorrido)",
        elemento9: "Protección solar",
        elemento10: "GPS, radio, mapa y botiquín",
    },
    {
        id: 4,
        nombre: "Cerro Piltriquitron",
        dificultad: "Media",
        altura: 1700,
        desnivel: 950,
        tiempo: 6.5,
        estaciones: 0,
        peso: 0,
        img: "/calculadoraMontana_DiPaola/img/galerias/cerroPiltriquitron.jpg",
        elemento1: "Mochila cómoda con varillas interiores",
        elemento2: "Bolsa de dormir o similar + aislante",
        elemento3: "Carpa de montaña con varillas de aluminio",
        elemento4: "Cubretecho extra para la carpa (zona muy lluviosa)",
        elemento5: "Ropa de abrigo y nieve para la cumbre",
        elemento6: "Zapatillas de trekking",
        elemento7: "Comida para 2 días y 1 noche",
        elemento8: "2 litros de agua",
        elemento9: "Protección solar",
        elemento10: "GPS, radio, mapa y botiquín",
    },
];
